import time

from app.tools.registry import execute_tool
from app.agent.context import AgentContext


def execute_plan(plan: dict, context: AgentContext) -> dict:
    """
    Execute the workflow generated by SANJI AI.

    Each task is executed sequentially and produces structured
    execution metadata such as status, duration and errors.
    """

    tasks = plan.get("tasks", [])

    results = []

    workflow_start = time.perf_counter()

    for task in tasks:

        task_id = task.get("id")
        description = task.get("description", "")
        tool_name = task.get("tool", "none")
        arguments = task.get("arguments", {})

        task_start = time.perf_counter()

        task_result = {
            "task_id": task_id,
            "description": description,
            "tool": tool_name,
            "status": "running",
            "result": None,
            "error": None,
            "duration_ms": 0,
        }

        # ========================================================
        # NO TOOL — FINAL SYNTHESIS
        # ========================================================

        if tool_name.lower() == "none":

            try:

                final_response = build_final_response(
                    plan=plan,
                    context=context
                )

                task_result["status"] = "completed"
                task_result["result"] = final_response

            except Exception as e:

                task_result["status"] = "failed"
                task_result["error"] = str(e)
                task_result["result"] = None

        # ========================================================
        # TOOL EXECUTION
        # ========================================================

        else:

            try:

                output = execute_tool(
                    tool_name,
                    arguments
                )

                if output.get("success"):

                    task_result["status"] = "completed"
                    task_result["result"] = output.get("result")

                else:

                    task_result["status"] = "failed"
                    task_result["error"] = output.get(
                        "error",
                        "Tool execution failed."
                    )

            except Exception as e:

                task_result["status"] = "failed"
                task_result["error"] = str(e)

        # ========================================================
        # TASK DURATION
        # ========================================================

        task_end = time.perf_counter()

        task_result["duration_ms"] = round(
            (task_end - task_start) * 1000,
            2
        )

        # ========================================================
        # STORE RESULT IN CONTEXT
        # ========================================================

        context.add_result(
            task_id=task_id,
            description=description,
            tool=tool_name,
            result=task_result["result"]
        )

        results.append(task_result)

        # ========================================================
        # STOP WORKFLOW IF A TASK FAILS
        # ========================================================

        if task_result["status"] == "failed":

            break

    # ============================================================
    # WORKFLOW SUMMARY
    # ============================================================

    workflow_end = time.perf_counter()

    total_duration_ms = round(
        (workflow_end - workflow_start) * 1000,
        2
    )

    completed_tasks = sum(
        1
        for result in results
        if result["status"] == "completed"
    )

    failed_tasks = sum(
        1
        for result in results
        if result["status"] == "failed"
    )

    if failed_tasks > 0:
        workflow_status = "failed"

    elif completed_tasks == len(tasks):
        workflow_status = "completed"

    else:
        workflow_status = "partial"

    return {
        "status": workflow_status,
        "total_tasks": len(tasks),
        "executed_tasks": len(results),
        "completed_tasks": completed_tasks,
        "failed_tasks": failed_tasks,
        "duration_ms": total_duration_ms,
        "results": results,
    }


# ================================================================
# FINAL RESPONSE BUILDER
# ================================================================

def build_final_response(
    plan: dict,
    context: AgentContext
) -> dict:
    """
    Combine previous task results into a structured final response.

    This deterministic version allows SANJI AI to operate without
    consuming external LLM credits.
    """

    previous_results = context.get_results()

    research_result = None
    calculation_result = None

    for item in previous_results:

        tool = item.get("tool")
        result = item.get("result")

        if tool == "research":

            research_result = result

        elif tool == "calculator":

            calculation_result = result

    response = {
        "summary": "Workflow completed successfully.",
        "research": research_result,
        "calculation": calculation_result,
    }

    # ============================================================
    # HUMAN-READABLE SUMMARY
    # ============================================================

    summary_parts = []

    # ------------------------------------------------------------
    # Research
    # ------------------------------------------------------------

    if research_result:

        if isinstance(research_result, dict):

            title = research_result.get("title")
            summary = research_result.get("summary")

            if title:

                summary_parts.append(
                    f"Research: {title}"
                )

            if summary:

                summary_parts.append(
                    f"Finding: {summary}"
                )

    # ------------------------------------------------------------
    # Calculation
    # ------------------------------------------------------------

    if calculation_result is not None:

        if isinstance(calculation_result, dict):

            value = calculation_result.get("result")

            if value is not None:

                summary_parts.append(
                    f"Calculated result: {value}"
                )

        else:

            summary_parts.append(
                f"Calculated result: {calculation_result}"
            )

    # ------------------------------------------------------------
    # Final summary
    # ------------------------------------------------------------

    if summary_parts:

        response["human_summary"] = "\n\n".join(
            summary_parts
        )

    else:

        response["human_summary"] = (
            "The workflow completed, but no tool results "
            "were available to summarize."
        )

    return response